## Task 1.A  -  Exploratory Data Analysis

In [3]:
# First necessary inputs

import os
import sys
import pandas as pd

In [6]:
# import csv files as dataframes

data_path = "data\input"
df_ex_std = pd.read_csv(os.path.join(data_path,'exogenous_standards.csv'))

# Display the first few rows of the DataFrame
df_ex_std.head()

  compound_id       mz  Retention_time
0         GU4   886.40             610
1         GU5  1048.45             753
2        GU14  1253.96            1500
3        GU15  1334.99            1551

In [7]:
df_data_mat = pd.read_csv(os.path.join(data_path,'internship_data_matrix.csv'))

# Display the first few rows of the DataFrame
df_data_mat.head()

,sample,FT-000,FT-001,FT-002,FT-003,FT-004,FT-005,FT-006,FT-007,FT-008,...,FT-242,FT-243,FT-244,FT-245,FT-246,FT-247,FT-248,FT-249,FT-250,FT-251
0,20241106-297-Blank1,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
1,20241106-297-Blank2,0.0,0.000000,0.0,5.770641,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.534493,0.0,0.0,0.0
2,20241106-297-Blank3,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.469501,0.0,0.0,0.0
3,20241106-297-Blank4,0.0,5.497865,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
4,20241106-297-Blank5,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0

In [9]:
df_feat_meta = pd.read_csv(os.path.join(data_path,'internship_feature_metadata.csv'))

# Display the first few rows of the DataFrame
df_feat_meta.head(10)

,feature,mz,mz max,mz min,mz std,rt,rt end,rt max,rt min,rt start,rt std
0,FT-000,359.108768,359.130591,359.090122,0.010955,543.846374,561.270879,546.697803,539.941156,528.714227,1.683901
1,FT-001,357.109546,357.130018,357.091871,0.010668,543.839157,563.021530,546.948017,540.038924,528.530311,1.662290
2,FT-002,889.649931,889.702216,889.601547,0.025552,609.099742,627.717251,611.746501,606.426553,596.789046,1.324647
3,FT-003,355.111928,355.132772,355.093653,0.010508,543.995269,566.951285,547.164503,540.681882,526.943213,1.609071
4,FT-004,888.645365,888.696941,888.600202,0.026161,609.255652,632.996442,612.008732,606.778809,595.461688,1.254684
5,FT-005,886.632460,886.683375,886.580667,0.026029,609.461289,638.067164,612.067644,606.711878,593.375215,1.287131
6,FT-006,887.640372,887.691598,887.593118,0.026411,609.387459,637.957134,612.049137,606.703800,594.204183,1.275731
7,FT-007,1051.742823,1051.806842,1051.688477,0.029811,753.193130,769.283091,755.954962,750.532679,740.815522,1.293041
8,FT-008,1050.739664,1050.800543,1050.686090,0.031277,753.457003,778.235971,756.242861,750.762498,739.039389,1.297824
9,FT-009,1049.732664,1049.793639,1049.679381,0.030903,753.593752,783.262112,756.185217,751.129772,737.980813,1.236249

In [11]:
df_acq_list = pd.read_csv(os.path.join(data_path,'internship_acquisition_list.csv'))

# Display the first few rows of the DataFrame
df_acq_list.head(10)

                     sample class                        id  order  batch
0       20241106-297-Blank1     B       20241106-297-Blank1      1      1
1       20241106-297-Blank2     B       20241106-297-Blank2      2      1
2       20241106-297-Blank3     B       20241106-297-Blank3      3      1
3       20241106-297-Blank4     B       20241106-297-Blank4    102      1
4       20241106-297-Blank5     B       20241106-297-Blank5    103      1
5       20241106-297-Blank6     B       20241106-297-Blank6    104      1
6  20241106-297-Diluted-QC1   dQC  20241106-297-Diluted-QC1      7      1
7  20241106-297-Diluted-QC2   dQC  20241106-297-Diluted-QC2      8      1
8  20241106-297-Diluted-QC3   dQC  20241106-297-Diluted-QC3      9      1
9  20241106-297-Diluted-QC4   dQC  20241106-297-Diluted-QC4     10      1